### ISSUE TITLE
./maincom_easy.tcl: 3: exec: prowish83: not found

### ISSUE THREAD

**Issue by nevrome** [zsiki/ComEasy#2]
Hi zsiki,

I'm trying to start ComEasy in my Ubuntu 14.04 environment but I get the errror

```
$./maincom_easy.tcl  
./maincom_easy.tcl: 3: exec: prowish83: not found
```

Is there a package missing? I installed Tcl via 

```
sudo apt-get install tcl8.5 tk8.5 expect
```

Thanks!

**Comment by lucaarcteam** [comment]
Hi @nevrome, you can try if the solution I described here (http://arc-team-open-research.blogspot.it/2016/05/comeasy-new-tool-for-total-station.html) is working also for you. Since Ubuntu is Debian derived it should work.

**Comment by nevrome** [comment]
Yes - that worked. Thanks!

Maybe you make a pull request with this change.

**Comment by zsiki** [comment]
I've changed in the source prowish83 to wish.
You can also start the script using wish e.g.

`wish maincom_easy.tcl`
